#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH="/Users/patrickneff/Library/Python/2.7/bin:$PATH"

alias ta="tmux attach-session -d"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export EDITOR="vim"

export GITHUB_URL=https://github-infosec.apple.com

export HASTE_SERVER=http://pastebin.apple.com

function rbgrep {
    grep $1 **/**.*rb
}
